import type { Metadata } from 'next';
import { Navbar } from '@/components/site/Navbar';
import { Footer } from '@/components/site/Footer';

export const metadata: Metadata = {
  title: 'Terms of Service — Blocklog',
  description: 'Blocklog Technologies Pvt. Ltd. Terms of Service.',
};

export default function TermsOfServicePage() {
  return (
    <>
      <Navbar />
      <main id="main-content" className="pt-24 pb-24 bg-slate-50 min-h-screen">
        <div className="site-container max-w-3xl pt-10">
          <div className="bg-white rounded-2xl p-8 sm:p-12 border border-slate-200 shadow-sm prose prose-slate max-w-none">
            <span className="eyebrow mb-2">Legal</span>
            <h1
              className="text-[2.25rem] font-bold text-slate-900 tracking-tight mb-6"
              style={{ fontFamily: 'var(--font-display)' }}
            >
              Terms of Service
            </h1>
            <p className="text-[13px] text-slate-500 mb-8">
              Effective Date: July 28, 2024 · Blocklog Security Technologies Pvt. Ltd.
            </p>

            <div className="space-y-6 text-[14px] text-slate-600 leading-relaxed">
              <section>
                <h2 className="text-[1.1rem] font-bold text-slate-900 mb-2">1. Terms Acceptance</h2>
                <p>
                  By accessing or using the Blocklog compliance platform, APIs, SDKs, or services, you agree to be bound by these Terms of Service. If you are accepting on behalf of an entity, you represent that you have authority to bind such entity.
                </p>
              </section>

              <section>
                <h2 className="text-[1.1rem] font-bold text-slate-900 mb-2">2. Service SLA &amp; Availability</h2>
                <p>
                  Blocklog guarantees 99.9% uptime for hosted API endpoints on Team and Scale tiers, and 99.99% for Enterprise SLA agreements.
                </p>
              </section>

              <section>
                <h2 className="text-[1.1rem] font-bold text-slate-900 mb-2">3. Cryptographic Integrity &amp; Verification</h2>
                <p>
                  Blocklog provides SHA-256 hash chaining and Merkle tree generation for evidence packages. You acknowledge that cryptographic integrity verification depends on preserving the original hash outputs and secret keys generated by your SDK configuration.
                </p>
              </section>
            </div>
          </div>
        </div>
      </main>
      <Footer />
    </>
  );
}